#!/bin/bash

TestEntier()									#
{										# Une fonction qui tourne en boucle tant que la variable
	Nombre=$1								# donnee n'est pas numerique
	until [ $Nombre -ne 0 -o $Nombre -eq 0 2>/dev/null ]			#
	do									#
		echo -n "$Nombre nest pas un entier, merci de changer : "	#
		read Nombre							#
	done									#
}

case $# in

	0)	echo "Merci de donner un nombre"	# Demande d'entrer un nombre si il n'y avait pas d'arguments
		echo -n "Entrer un nombre : "		# 
		read var				#
		TestEntier "$var"			# Lance le test avec notre nouvelle variable
		var="$Nombre";;				#

	1)	var="$1"				#
		TestEntier "$var"			# Lance directement le test si il y avait un argument
		var="$Nombre";;				#

	*)	echo "trop d'argument"			# Arrete le programme si trop d'argument
		exit;;					#
esac

while [ "$var" -ne "1" ]	# Boucle tant que le resultat n'est pas egal a 1
do
	modulo=$(($var % 2))	# Si le modulo egal a 0 alors le nombre est pai

	if [ "$modulo" -eq "0" ]
	then
		echo -n "$var est pair, "	#
		var=$(($var / 2))		# Si le nombre est pair on le divise par deux
		echo "j'obtiens donc $var"	# Et on affiche le resultat
	else
		echo -n "$var est impair, "	#
		var=$((($var * 3) + 1))		# Si le nombre est impair on le multiplie par trois et on ajoute un
		echo "J'obtiens donc $var"	# Et on affiche le resultat
	fi
done
