#!/bin/bash

case $# in
		1) 	if [ ! -f $1 ]						#
			then							#Si le fichier n'existe pas on affiche l'erreur
					echo "$1 n'est pas un fichier"		#
					exit 2					#
			elif [ -r $1 ]					# Si le fichier existe et qu'on a le droit de le lire
			then						# On affiche les lignes 5 a 10
				head "$1" | tail -n 6			#
			else										#
				echo "$1 n'existe pas ou vous n'avez pas le droit de le lire"		#Sinon on affiche l'erreur
				exit 3									#
			fi;;

		*)	echo "Usage : cub [nom du fichier] Permet d'afficher aux lignes 5 a 10 du fichier" # Si nombre d'argument different de 1
			exit 1;
esac

